### ISSUE TITLE
Minoc relies on GMSClient.getGroups() which is not implemented

### ISSUE THREAD

**Issue by at88mph** [opencadc/storage-inventory#107]
Issuing a HEAD request to a Minoc resource causes a call to `getUsersGroups()` in `checkReadPermission()`, which relies on the `GMSClient.getGroups()` function.  This method is not implemented.

Consequently, this also prevents JDBC connections from being returned to the pool.  The default pool has two connections, so two HEAD requests will cause Minoc to hang.

**Comment by pdowler** [comment]
Minoc has recentyl been changed to do permission checks, but not correctly; I will chalk that up to in-progress work that has been done in the wrong order and integration tests not actually being run... sigh.

What do you mean by "this method is not implemented"? Does it throw or return null?

In any case, I don't see how that uses up the JDBC pool when there is a single auto-commit query that uses the DataSource (ArtifactAction.getArtifact line 431)

**Comment by at88mph** [comment]
The method returns an `UnsupportedOperationException`:
https://github.com/opencadc/ac/blob/master/cadc-access-control/src/main/java/ca/nrc/cadc/ac/client/GMSClient.java#L205

As for where the pool exhaustion is coming from I don't know.  I just know that after to `HEAD` requests there are no more connections available.  This is with a `cadc-storage-adapter-fs` site.

**Comment by pdowler** [comment]
fixed to use GroupClient from cadc-gms
