### ISSUE TITLE
cadc-storage-adapter-fs: FileSystemIterator Files.getAttributeView does not work on macOS

### ISSUE THREAD

**Issue by at88mph** [opencadc/storage-inventory#111]
The `cadc-storage-adapter-fs` module relies on a `Files` API from the installed JDK.  The macOS file system does not lend itself to the extended attributes that way, but rather relies on the `xattrs` API.  We would need a JNI solution:
https://github.com/leiless/xattr4j

To work properly.  Understandably this will not be run on macOS, but it makes development a bit of a pain.

**Comment by pdowler** [comment]
Tests for OpaqueFileSystemStorageAdapter were created under intTest so the local system doesn't need xattr support to build... will do the same with remaining test code asap. Work on the adapter itself still requires a system with xattr to run the intTest(s), but it helps.

Does the pure java code work at runtime in a docker container on macOS? e.g. Can you create a suitable FS for the data?
