### ISSUE TITLE
Fenwick: Support multiple instances on site

### ISSUE THREAD

**Issue by at88mph** [opencadc/storage-inventory#158]
Due to the nature of the `HarvestState`, only one Fenwick can be run on a single site.  Currently the `HarvestState` is preserved per Item (i.e. `Artifact.class`, `DeletedEvent.class`, etc), but perhaps should be harvested per _process_ instead to allow multiple instances to be run.

There are no workarounds for this currently.

**Comment by at88mph** [comment]
My use case for this was to allow multiple Fenwick instances each with its own include SQL statements.  Maybe this can be overcome by writing a more complex SQL in a single Fenwick that can have `OR` statements?

**Comment by pdowler** [comment]
This issue now covered by #166
