### ISSUE TITLE
tantar: can't distinguish between 'not authorized' and 'no results found'

### ISSUE THREAD

**Issue by jburke-cadc** [opencadc/storage-inventory#165]
When tantar queries a storage site running a TAP service, it cannot tell if the caller is authorized to do the query but no query results were found, or if the caller is not authorized to do the query. Both result in zero rows returned. A incorrect certificate, or an out of date certificate, can result in all data for the archive(s) queried being deleted from the inventory database.

**Comment by pdowler** [comment]
This is really due to the subtle behaviour of the /ad TAP service, which magically filters queries. It could be modified to respond with an error instead of returning a zero-row result.

**Comment by pdowler** [comment]
The /ad TA service has been changed to respond with a 403 AccessControlException.
