### ISSUE TITLE
cadc-storage-adapter-ad: Unauthorized calls not returning properly.

### ISSUE THREAD

**Issue by at88mph** [opencadc/storage-inventory#185]
The `AdStorageAdapter` is not handling `AccessControlException`s properly, or is failing to propagating them.  The call to the `data` web service could result in a 403 or a 401, which should be sent along to the client.  Currently it returns a successful result code, with an `Unauthorized` message.

**Comment by pdowler** [comment]
AdStorageAdapter needs to use delegated credentials correctly when proxying the call to `data`
