### ISSUE TITLE
fenwick: {user.home}/config/artifact-filter.sql removed by integration test

### ISSUE THREAD

**Issue by yeunga** [opencadc/storage-inventory#224]
InventoryHarvesterTest.runIncludeArtifacts() removes any existing {user.home}/config/artifact-filter.sql. This is not desirable.

One solution that Pat suggested was when running intTest, to have that inside the project and change the user.home system prop during test run.

**Comment by pdowler** [comment]
Yes - since the file is created by the test, it should be contained in the project. If a single test/file is needed :

src/intTest/resources/config/artifact-filter.sql

then in the intTest, `System.setProperty("user.home", "build/
