### ISSUE TITLE
cadc-storage-adapter-fs: cannot compute MD5 on the fly

### ISSUE THREAD

**Issue by pdowler** [opencadc/storage-inventory#33]
Computing the MD5 checksum on the fly while iterating cannot perform adequately.

Instead:
* store the checksum using a file system attribute at the end of a write (see cavern)
* return the xattr value in the iterator (consistency with inventory)
* compute the checksum on the stream during a read and reset the checksum xattr; log this at WARN level at least (detect corruption?)

Stretch feature:
* implement an async process that scans the file system and verifies checksum attributes pre-emptively; once the main feature above is implemented this should be split into it's own RFE.

**Comment by hjeeves** [comment]
Response is here: https://github.com/opencadc/storage-inventory/pull/83

**Comment by pdowler** [comment]
fixed
