### ISSUE TITLE
cadc-storage-adapter-fs: must hide temp files until complete

### ISSUE THREAD

**Issue by pdowler** [opencadc/storage-inventory#57]
The filesystem adapter writes to a temp file and performs an atomic move to final destination.

However, the temp file is visible within the normal tree during the write so will be picked up by the iterator method (e.g. file-validate process). 

Recommend: divide the configured root directory into two separate sub dirs, e.g. "complete" and "transactions", create temp files in "transactions", and move them to "complete".

**Comment by hjeeves** [comment]
opening issue - tinypm story 2697, task 13024
