### ISSUE TITLE
Zero length files are not properly handled

### ISSUE THREAD

**Issue by at88mph** [opencadc/storage-inventory#62]
Issuing a PUT for a zero length file causes the request to hang.

```bash
$ rm -f /tmp/zerosize.txt
$ touch /tmp/zerosize.txt
$ curl <auth> @zerosize.txt https://myserver.com/minoc/files/zerosize.txt
```

**Comment by pdowler** [comment]
It is unclear if zero length files are supposed to be supported in storage or not.

**Comment by at88mph** [comment]
OK.  Either way, an error needs to be thrown if it's not supported, correct?

**Comment by pdowler** [comment]
Yes, it should accept it or respond with an error. Which is the reason for the TBD tag.

Is the above fail with a specific storage adpater or multiple?

**Comment by at88mph** [comment]
That is with the `ceph-storage-adapter-fs`.

**Comment by pdowler** [comment]
Could not reproduce the hang - might have been a bug in ThreadedIO that was accidetnally fixed :-)

Currently: the Artifact constructor throws an IllegalArgumentException for non-positive contentLength and as a result minoc rejects a zero-length file with a 400.
